nelmio_cors:
    defaults:
        allow_origin: ['*'] # Autorise toutes les origines. Remplace par des domaines spécifiques si besoin.
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PATCH'] # Méthodes HTTP autorisées.
        allow_headers: ['Content-Type', 'Authorization'] # En-têtes autorisés.
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': # Applique cette configuration aux routes commençant par /api/
            allow_origin: ['*'] # Autorise toutes les origines pour les API.
            allow_methods: ['GET', 'POST', 'PATCH', 'OPTIONS'] # Méthodes HTTP autorisées pour les API.
            allow_headers: ['Content-Type', 'Authorization'] # En-têtes autorisés pour les API.
